// * ------------ @NEXT.JS -----------------------//
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
// * ------------ @NEXT.JS -----------------------//

// * ------------ @PACKAGES -----------------------//
import { ThemeProvider } from 'next-themes';
// * ------------ @PACKAGES -----------------------//

// * ------------ @FONTS -----------------------//
import { Inter, Roboto } from 'next/font/google';
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});
const inter = Inter({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});
// * ------------ @FONTS -----------------------//

// * ------------ @STYLES -----------------------//
import '@/styles/global.style.css';
import '@/styles/toggle-switch.style.css';
import '@/styles/ticker-tape.style.css';
import '@styles/market-gauge.style.css';
// * ------------ @STYLES -----------------------//

// * ------------ @COMPONENTS -----------------------//
import HeaderComponent from '@/components/Header.component';
import FooterComponent from '@/components/Footer.component';
import TickerTapeComponent from '@/components/TickerTape.component';
// * ------------ @COMPONENTS -----------------------//

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <TickerTapeComponent />
          <HeaderComponent />
          {children}
          <FooterComponent />
        </ThemeProvider>
      </body>
    </html>
  );
}
